#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-dm-types
Version  : 1.2.2
Release  : 1
URL      : https://rubygems.org/downloads/dm-types-1.2.2.gem
Source0  : https://rubygems.org/downloads/dm-types-1.2.2.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-addressable
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-dm-core
BuildRequires : rubygem-dm-migrations
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support

%description
= dm-types
DataMapper plugin providing many extra types for use in data models.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n dm-types-1.2.2
gem spec %{SOURCE0} -l --ruby > rubygem-dm-types.gemspec

%build
gem build rubygem-dm-types.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
dm-types-1.2.2.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/dm-types-1.2.2.gem
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/APIKey/cdesc-APIKey.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/APIKey/generate-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/BCryptHash/cdesc-BCryptHash.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/BCryptHash/dump-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/BCryptHash/load-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/BCryptHash/primitive%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/BCryptHash/typecast_to_primitive-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/CommaSeparatedList/cdesc-CommaSeparatedList.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/CommaSeparatedList/dump-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/Csv/cdesc-Csv.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/Csv/dump-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/Csv/load-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/Csv/primitive%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/DirtyMinder/Hooker/cdesc-Hooker.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/DirtyMinder/Hooker/extended-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/DirtyMinder/Hooker/track-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/DirtyMinder/cdesc-DirtyMinder.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/DirtyMinder/hook_value-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/DirtyMinder/set%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/Enum/cdesc-Enum.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/Enum/dump-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/Enum/load-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/Enum/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/Enum/typecast_to_primitive-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/EpochTime/cdesc-EpochTime.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/EpochTime/custom%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/EpochTime/datetime_to_time-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/EpochTime/dump-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/EpochTime/load-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/EpochTime/typecast-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/FilePath/cdesc-FilePath.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/FilePath/dump-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/FilePath/load-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/FilePath/primitive%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/FilePath/typecast_to_primitive-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/FilePath/valid%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/Flag/cdesc-Flag.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/Flag/dump-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/Flag/load-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/Flag/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/Flag/typecast-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/Flags/ClassMethods/%5b%5d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/Flags/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/Flags/cdesc-Flags.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/Flags/custom%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/Flags/included-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/IPAddress/cdesc-IPAddress.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/IPAddress/dump-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/IPAddress/load-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/IPAddress/primitive%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/IPAddress/typecast_to_primitive-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/IPAddress/valid%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/JSON/cdesc-JSON.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/JSON/custom%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/JSON/dump-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/JSON/load-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/JSON/primitive%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/JSON/typecast_to_primitive-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/JSON/valid%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/Json/cdesc-Json.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/Json/custom%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/Json/dump-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/Json/load-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/Json/primitive%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/Json/typecast_to_primitive-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/Json/valid%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/ParanoidBoolean/bind-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/ParanoidBoolean/cdesc-ParanoidBoolean.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/ParanoidDateTime/bind-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/ParanoidDateTime/cdesc-ParanoidDateTime.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/Regexp/cdesc-Regexp.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/Regexp/dump-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/Regexp/load-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/Regexp/typecast-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/Slug/cdesc-Slug.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/Slug/escape-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/Slug/typecast-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/URI/cdesc-URI.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/URI/custom%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/URI/dump-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/URI/load-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/URI/primitive%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/URI/typecast_to_primitive-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/URI/valid%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/UUID/cdesc-UUID.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/UUID/dump-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/UUID/load-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/UUID/primitive%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/UUID/typecast_to_primitive-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/UUID/valid%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/Yaml/cdesc-Yaml.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/Yaml/custom%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/Yaml/dump-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/Yaml/load-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/Yaml/typecast-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Property/cdesc-Property.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Types/Paranoid/Base/_destroy-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Types/Paranoid/Base/cdesc-Base.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Types/Paranoid/Base/included-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Types/Paranoid/Base/paranoid_destroy-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Types/Paranoid/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Types/Paranoid/ClassMethods/inherited-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Types/Paranoid/ClassMethods/paranoid_properties-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Types/Paranoid/ClassMethods/set_paranoid_property-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Types/Paranoid/ClassMethods/with_deleted-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Types/Paranoid/cdesc-Paranoid.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/Types/cdesc-Types.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/DataMapper/cdesc-DataMapper.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/Object/cdesc-Object.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/page-LICENSE.ri
/usr/lib64/ruby/gems/2.2.0/doc/dm-types-1.2.2/ri/page-README_rdoc.ri
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/.gitignore
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/README.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/dm-types.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/lib/dm-types.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/lib/dm-types/api_key.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/lib/dm-types/bcrypt_hash.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/lib/dm-types/comma_separated_list.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/lib/dm-types/csv.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/lib/dm-types/enum.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/lib/dm-types/epoch_time.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/lib/dm-types/file_path.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/lib/dm-types/flag.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/lib/dm-types/ip_address.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/lib/dm-types/json.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/lib/dm-types/paranoid/base.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/lib/dm-types/paranoid_boolean.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/lib/dm-types/paranoid_datetime.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/lib/dm-types/regexp.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/lib/dm-types/slug.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/lib/dm-types/support/dirty_minder.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/lib/dm-types/support/flags.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/lib/dm-types/uri.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/lib/dm-types/uuid.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/lib/dm-types/yaml.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/spec/fixtures/api_user.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/spec/fixtures/article.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/spec/fixtures/bookmark.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/spec/fixtures/invention.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/spec/fixtures/network_node.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/spec/fixtures/person.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/spec/fixtures/software_package.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/spec/fixtures/ticket.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/spec/fixtures/tshirt.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/spec/integration/api_key_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/spec/integration/bcrypt_hash_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/spec/integration/comma_separated_list_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/spec/integration/dirty_minder_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/spec/integration/enum_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/spec/integration/epoch_time_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/spec/integration/file_path_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/spec/integration/flag_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/spec/integration/ip_address_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/spec/integration/json_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/spec/integration/slug_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/spec/integration/uri_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/spec/integration/uuid_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/spec/integration/yaml_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/spec/rcov.opts
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/spec/shared/flags_shared_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/spec/shared/identity_function_group.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/spec/spec.opts
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/spec/unit/bcrypt_hash_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/spec/unit/csv_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/spec/unit/enum_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/spec/unit/epoch_time_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/spec/unit/file_path_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/spec/unit/flag_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/spec/unit/ip_address_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/spec/unit/json_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/spec/unit/paranoid_boolean_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/spec/unit/paranoid_datetime_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/spec/unit/regexp_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/spec/unit/uri_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/spec/unit/uuid_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/spec/unit/yaml_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/tasks/spec.rake
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/tasks/yard.rake
/usr/lib64/ruby/gems/2.2.0/gems/dm-types-1.2.2/tasks/yardstick.rake
/usr/lib64/ruby/gems/2.2.0/specifications/dm-types-1.2.2.gemspec
